spring:
  r2dbc:
    url: r2dbc:mysql://120.46.159.231:3306/2022212808?createDatabaseIfNotExist=true'
    username: 2022212808
    password: 2022212808
  data:
    redis:
      host: 120.46.159.231
      port: 6379
      username: default
      password: 2046
      database: 9
springdoc:
  api-docs:
    path: /SERVICENAME/v3/api-docs


logging:
  level:
    io.r2dbc:

my:
  key: abc